-- SQL for Supabase Migration
-- Run this in the Supabase SQL Editor

CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    region TEXT,
    type TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    verified BOOLEAN DEFAULT TRUE,
    phone_number TEXT,
    description TEXT,
    naver_smartplace_link TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT stores_name_address_key UNIQUE (name, address)
);

-- Enable RLS (Optional but recommended)
ALTER TABLE stores ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Allow public read access" ON stores FOR SELECT USING (true);

-- Create policy to allow service role to manage data
CREATE POLICY "Allow service role management" ON stores FOR ALL USING (auth.role() = 'service_role');
